# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata
from ...requests.split_override_config import SplitOverrideConfigParams
from ...types.processor_version_string import ProcessorVersionString


class SplitRunsCreateRequestSplitterParams(typing_extensions.TypedDict):
    """
    Reference to an existing splitter. One of `splitter` or `config` must be provided.
    """

    id: str
    """
    The ID of the splitter to use.
    """

    version: typing_extensions.NotRequired[ProcessorVersionString]
    override_config: typing_extensions.NotRequired[
        typing_extensions.Annotated[SplitOverrideConfigParams, FieldMetadata(alias="overrideConfig")]
    ]
    """
    Optional partial configuration override. Only the fields you provide will override the splitter's saved configuration. For example, you can pass only `splitRules` without providing `splitClassifications`.
    """
