# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel, UnionMetadata
from .created_at import CreatedAt


class BatchRunEntityVersion_ExtractorVersionSummary(UncheckedBaseModel):
    """
    The version of the extractor, classifier, or splitter that was run.

    **Availability:** Present when an entity was provided when creating the batch run.
    """

    object: typing.Literal["extractor_version_summary"] = "extractor_version_summary"
    id: str
    description: typing.Optional[str] = None
    version: str
    extractor_id: typing_extensions.Annotated[str, FieldMetadata(alias="extractorId")] = pydantic.Field(
        alias="extractorId"
    )
    created_at: typing_extensions.Annotated[CreatedAt, FieldMetadata(alias="createdAt")] = pydantic.Field(
        alias="createdAt"
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class BatchRunEntityVersion_ClassifierVersionSummary(UncheckedBaseModel):
    """
    The version of the extractor, classifier, or splitter that was run.

    **Availability:** Present when an entity was provided when creating the batch run.
    """

    object: typing.Literal["classifier_version_summary"] = "classifier_version_summary"
    id: str
    description: typing.Optional[str] = None
    version: str
    classifier_id: typing_extensions.Annotated[str, FieldMetadata(alias="classifierId")] = pydantic.Field(
        alias="classifierId"
    )
    created_at: typing_extensions.Annotated[CreatedAt, FieldMetadata(alias="createdAt")] = pydantic.Field(
        alias="createdAt"
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class BatchRunEntityVersion_SplitterVersionSummary(UncheckedBaseModel):
    """
    The version of the extractor, classifier, or splitter that was run.

    **Availability:** Present when an entity was provided when creating the batch run.
    """

    object: typing.Literal["splitter_version_summary"] = "splitter_version_summary"
    id: str
    description: typing.Optional[str] = None
    version: str
    splitter_id: typing_extensions.Annotated[str, FieldMetadata(alias="splitterId")] = pydantic.Field(
        alias="splitterId"
    )
    created_at: typing_extensions.Annotated[CreatedAt, FieldMetadata(alias="createdAt")] = pydantic.Field(
        alias="createdAt"
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


BatchRunEntityVersion = typing_extensions.Annotated[
    typing.Union[
        BatchRunEntityVersion_ExtractorVersionSummary,
        BatchRunEntityVersion_ClassifierVersionSummary,
        BatchRunEntityVersion_SplitterVersionSummary,
    ],
    UnionMetadata(discriminant="object"),
]
