# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class CellFormatting(UncheckedBaseModel):
    """
    Structured formatting for an Excel table cell
    """

    bold: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the cell text is bold.
    """

    italic: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the cell text is italic.
    """

    font_color: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="fontColor")] = pydantic.Field(
        alias="fontColor", default=None
    )
    """
    Cell font color as a hex string.
    """

    background_color: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="backgroundColor")] = (
        pydantic.Field(alias="backgroundColor", default=None)
    )
    """
    Cell background color as a hex string.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
