# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .classification_next_entry import ClassificationNextEntry
from .classify_step_definition_config import ClassifyStepDefinitionConfig


class ClassifyStepDefinition(UncheckedBaseModel):
    """
    Classifies documents using a classifier. Routes to different next steps based on classification result.

    The classifier reference must include a pinned `version` — `"latest"` is not supported for `CLASSIFY` steps. Use a specific semver string (e.g. `"0.1"`) or `"draft"`. This is because classification IDs used for routing are tied to a specific processor version's config.

    See the [Classify step docs](https://docs.extend.ai/2026-02-09/workflows/configuring-workflows#classify).
    """

    name: str
    config: typing.Optional[ClassifyStepDefinitionConfig] = pydantic.Field(default=None)
    """
    Optional on create/update. Required before the workflow can be deployed. Omitted in responses when the step is not yet configured.
    
    Reference to the classifier used by this step. The `next[].classificationId` values must match classification `id` values (not `type` strings) from the referenced classifier's configuration. For example, if the classifier defines `{ "id": "cls_invoice", "type": "invoice" }`, use `"cls_invoice"` as the `classificationId`.
    
    The classifier `version` is required and must be a pinned version (semver like `"0.1"` or `"draft"`). `"latest"` is not allowed.
    
    See the [Classify step docs](https://docs.extend.ai/2026-02-09/workflows/configuring-workflows#classify).
    """

    next: typing.Optional[typing.List[ClassificationNextEntry]] = pydantic.Field(default=None)
    """
    Can only be set when `config` is present. Each entry must include a `classificationId` matching a classification `id` from the referenced classifier's configuration. Use the classification's stable `id` (e.g. `"cls_invoice"`), not the `type` string.
    
    See the [Classify step docs](https://docs.extend.ai/2026-02-09/workflows/configuring-workflows#classify).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
