# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .conditional_next_entry import ConditionalNextEntry
from .conditional_step_definition_config import ConditionalStepDefinitionConfig


class ConditionalStepDefinition(UncheckedBaseModel):
    """
    Routes to different next steps based on ordered conditional branches evaluated against upstream step outputs.

    See the [Conditional step docs](https://docs.extend.ai/2026-02-09/workflows/configuring-workflows#conditional).
    """

    name: str
    config: ConditionalStepDefinitionConfig
    next: typing.Optional[typing.List[ConditionalNextEntry]] = pydantic.Field(default=None)
    """
    Each entry should include a `conditionId` matching a `config.conditions[].id` value.
    
    See the [Conditional step docs](https://docs.extend.ai/2026-02-09/workflows/configuring-workflows#conditional).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
