# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class DataRetentionMode(enum.StrEnum):
    """
    The retention mode for this run:
    * `workspace_default` - Use the workspace's configured retention policy.
    * `zero` - Do not retain supported run data after processing.
    """

    WORKSPACE_DEFAULT = "workspace_default"
    ZERO = "zero"
    _UNKNOWN = "__DATARETENTIONMODE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "DataRetentionMode":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        workspace_default: typing.Callable[[], T_Result],
        zero: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is DataRetentionMode.WORKSPACE_DEFAULT:
            return workspace_default()
        if self is DataRetentionMode.ZERO:
            return zero()
        return _unknown_member(self._value_)
