# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .data_retention_mode import DataRetentionMode


class DataRetention(UncheckedBaseModel):
    """
    Controls data retention for this run. When omitted or set to `workspace_default`, Extend uses your workspace's configured retention policy. Set `mode` to `zero` to request zero data retention for the run, which deletes supported run data after processing instead of retaining it under the workspace policy.

    Zero data retention is only available for eligible organizations and plans. If your organization is not eligible, the request will fail with a 400 error.
    """

    mode: typing.Optional[DataRetentionMode] = pydantic.Field(default=None)
    """
    The retention mode for this run:
    * `workspace_default` - Use the workspace's configured retention policy.
    * `zero` - Do not retain supported run data after processing.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
