# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class EditRunOutputEditedFile(UncheckedBaseModel):
    """
    Information about the edited output file.
    """

    id: str = pydantic.Field()
    """
    The ID of the edited output file.
    """

    presigned_url: typing_extensions.Annotated[str, FieldMetadata(alias="presignedUrl")] = pydantic.Field(
        alias="presignedUrl"
    )
    """
    A presigned URL to download the edited file. Expires after 15 minutes.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
