# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .edit_dependent_required import EditDependentRequired


class EditConditionalClause(UncheckedBaseModel):
    """
    Recursive conditional clause for edit schemas. Use these clauses with root-level `if` / `then` / `else`,
    `dependentRequired`, and logical combinators to model conditional field requirements. Nested clauses are
    supported up to 8 levels.
    """

    properties: typing.Optional[typing.Dict[str, "EditConditionalPropertySchema"]] = pydantic.Field(default=None)
    """
    Conditional field constraints keyed by top-level property name.
    """

    required: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of fields that must be present when this clause applies.
    """

    dependent_required: typing_extensions.Annotated[
        typing.Optional[EditDependentRequired], FieldMetadata(alias="dependentRequired")
    ] = pydantic.Field(alias="dependentRequired", default=None)
    if_: typing_extensions.Annotated[typing.Optional["EditConditionalClause"], FieldMetadata(alias="if")] = (
        pydantic.Field(alias="if", default=None)
    )
    then: typing.Optional["EditConditionalClause"] = None
    else_: typing_extensions.Annotated[typing.Optional["EditConditionalClause"], FieldMetadata(alias="else")] = (
        pydantic.Field(alias="else", default=None)
    )
    all_of: typing_extensions.Annotated[
        typing.Optional[typing.List["EditConditionalClause"]], FieldMetadata(alias="allOf")
    ] = pydantic.Field(alias="allOf", default=None)
    """
    List of nested conditional clauses that must all match.
    """

    one_of: typing_extensions.Annotated[
        typing.Optional[typing.List["EditConditionalClause"]], FieldMetadata(alias="oneOf")
    ] = pydantic.Field(alias="oneOf", default=None)
    """
    List of nested conditional clauses where exactly one must match.
    """

    any_of: typing_extensions.Annotated[
        typing.Optional[typing.List["EditConditionalClause"]], FieldMetadata(alias="anyOf")
    ] = pydantic.Field(alias="anyOf", default=None)
    """
    List of nested conditional clauses where at least one must match.
    """

    not_: typing_extensions.Annotated[typing.Optional["EditConditionalClause"], FieldMetadata(alias="not")] = (
        pydantic.Field(alias="not", default=None)
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .edit_conditional_object_property_schema import EditConditionalObjectPropertySchema  # noqa: E402, I001
from .edit_conditional_property_schema import EditConditionalPropertySchema  # noqa: E402, I001

update_forward_refs(
    EditConditionalClause,
    EditConditionalObjectPropertySchema=EditConditionalObjectPropertySchema,
    EditConditionalPropertySchema=EditConditionalPropertySchema,
)
