# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class EditSchemaGenerationMappingMatch(UncheckedBaseModel):
    """
    A successful mapping between an input schema path and a detected form field.
    """

    input_path: typing_extensions.Annotated[str, FieldMetadata(alias="inputPath")] = pydantic.Field(alias="inputPath")
    """
    The path from the provided `inputSchema`.
    """

    form_field_key: typing_extensions.Annotated[str, FieldMetadata(alias="formFieldKey")] = pydantic.Field(
        alias="formFieldKey"
    )
    """
    The detected form field key matched to the input path.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
