# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .extract_advanced_options import ExtractAdvancedOptions
from .extract_base_processor import ExtractBaseProcessor
from .json_object import JsonObject
from .parse_config import ParseConfig


class ExtractOverrideConfigJson(UncheckedBaseModel):
    """
    Partial configuration override for an existing extractor. All fields are optional — only the fields you provide will override the extractor's saved configuration.
    For example, you can pass only `advancedOptions` or `extractionRules` without providing a `schema`.
    """

    base_processor: typing_extensions.Annotated[
        typing.Optional[ExtractBaseProcessor], FieldMetadata(alias="baseProcessor")
    ] = pydantic.Field(alias="baseProcessor", default=None)
    base_version: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="baseVersion")] = (
        pydantic.Field(alias="baseVersion", default=None)
    )
    """
    The version of the `"extraction_performance"` or `"extraction_light"` processor to use. If not provided, the latest stable version for the selected `baseProcessor` will be used automatically. See [Extraction Changelog](https://docs.extend.ai/2026-02-09/changelog/extraction/extraction-performance) for more details.
    """

    extraction_rules: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="extractionRules")] = (
        pydantic.Field(alias="extractionRules", default=None)
    )
    """
    Custom rules to guide the extraction process in natural language.
    """

    schema_: typing_extensions.Annotated[typing.Optional[JsonObject], FieldMetadata(alias="schema")] = pydantic.Field(
        alias="schema", default=None
    )
    """
    JSON Schema definition of the data to extract.
    
    See the [JSON Schema guide](https://docs.extend.ai/2026-02-09/product/extraction/schema/json-schema) for details and examples of schema configuration.
    """

    advanced_options: typing_extensions.Annotated[
        typing.Optional[ExtractAdvancedOptions], FieldMetadata(alias="advancedOptions")
    ] = pydantic.Field(alias="advancedOptions", default=None)
    """
    Advanced configuration options.
    """

    parse_config: typing_extensions.Annotated[typing.Optional[ParseConfig], FieldMetadata(alias="parseConfig")] = (
        pydantic.Field(alias="parseConfig", default=None)
    )
    """
    Configuration options for the parsing process.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
