# This file was auto-generated by Fern from our API Definition.

import typing

ExtractConfigJsonBaseProcessor = typing.Union[typing.Literal["extraction_performance", "extraction_light"], typing.Any]
