# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .edit_schema_generation_config import EditSchemaGenerationConfig
from .edit_schema_generation_response import EditSchemaGenerationResponse
from .file_summary import FileSummary
from .form_detection_run_metrics import FormDetectionRunMetrics
from .form_detection_run_status import FormDetectionRunStatus
from .run_usage import RunUsage


class FormDetectionRun(UncheckedBaseModel):
    """
    A run that detects fields in a PDF form and generates an edit schema.
    """

    object: typing.Literal["form_detection_run"] = pydantic.Field(default="form_detection_run")
    """
    The type of object. Will always be `"form_detection_run"`.
    """

    id: str = pydantic.Field()
    """
    A unique identifier for the form detection run.
    
    Example: `"sgr_xK9mLPqRtN3vS8wF5hB2cQ"`
    """

    file: FileSummary = pydantic.Field()
    """
    The input PDF submitted for form detection.
    """

    status: FormDetectionRunStatus = pydantic.Field()
    """
    The status of the form detection run:
    * `"PROCESSING"` - The form is still being analyzed
    * `"PROCESSED"` - Form detection completed successfully
    * `"FAILED"` - Form detection failed (see `failureReason` for details)
    """

    failure_reason: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="failureReason")] = (
        pydantic.Field(alias="failureReason", default=None)
    )
    """
    The reason for failure.
    
    **Availability:** Present when `status` is `"FAILED"`.
    
    Possible values include:
    * `UNABLE_TO_DOWNLOAD_FILE`
    * `FILE_TYPE_NOT_SUPPORTED`
    * `FILE_SIZE_TOO_LARGE`
    * `CORRUPT_FILE`
    * `FIELD_DETECTION_ERROR`
    * `PASSWORD_PROTECTED_FILE`
    * `FAILED_TO_CONVERT_TO_PDF`
    * `EMPTY_SCHEMA`
    * `INTERNAL_ERROR`
    * `INVALID_OPTIONS`
    * `OUT_OF_CREDITS`
    
    **Note:** Additional failure reasons may be added in the future. Your integration should handle unknown values gracefully.
    """

    failure_message: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="failureMessage")] = (
        pydantic.Field(alias="failureMessage", default=None)
    )
    """
    A human-readable description of the failure.
    
    **Availability:** Present when `status` is `"FAILED"`.
    """

    config: EditSchemaGenerationConfig = pydantic.Field()
    """
    The configuration used for this form detection run, including any default values that were applied.
    """

    output: typing.Optional[EditSchemaGenerationResponse] = pydantic.Field(default=None)
    """
    The detected schema and optional mapping metadata.
    
    **Availability:** Present when `status` is `"PROCESSED"`.
    """

    metrics: typing.Optional[FormDetectionRunMetrics] = pydantic.Field(default=None)
    """
    Metrics about the form detection process.
    
    **Availability:** Present when `status` is `"PROCESSED"`.
    """

    usage: typing.Optional[RunUsage] = pydantic.Field(default=None)
    """
    Usage credits consumed by this form detection run.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


update_forward_refs(FormDetectionRun)
