# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class LegacyBatchProcessorRunStatus(enum.StrEnum):
    """
    The current status of the batch processor run:
    * `"PENDING"` - The batch processor run is waiting to start
    * `"PROCESSING"` - The batch processor run is in progress
    * `"PROCESSED"` - The batch processor run completed successfully
    * `"FAILED"` - The batch processor run encountered an error
    """

    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    FAILED = "FAILED"
    _UNKNOWN = "__LEGACYBATCHPROCESSORRUNSTATUS_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "LegacyBatchProcessorRunStatus":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        pending: typing.Callable[[], T_Result],
        processing: typing.Callable[[], T_Result],
        processed: typing.Callable[[], T_Result],
        failed: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is LegacyBatchProcessorRunStatus.PENDING:
            return pending()
        if self is LegacyBatchProcessorRunStatus.PROCESSING:
            return processing()
        if self is LegacyBatchProcessorRunStatus.PROCESSED:
            return processed()
        if self is LegacyBatchProcessorRunStatus.FAILED:
            return failed()
        return _unknown_member(self._value_)
