# This file was auto-generated by Fern from our API Definition.

import typing

LegacySplitterConfigBaseProcessor = typing.Union[typing.Literal["splitting_performance", "splitting_light"], typing.Any]
