# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class LegacySortByEnum(enum.StrEnum):
    UPDATED_AT = "updatedAt"
    CREATED_AT = "createdAt"
    _UNKNOWN = "__LEGACYSORTBYENUM_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "LegacySortByEnum":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        updated_at: typing.Callable[[], T_Result],
        created_at: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is LegacySortByEnum.UPDATED_AT:
            return updated_at()
        if self is LegacySortByEnum.CREATED_AT:
            return created_at()
        return _unknown_member(self._value_)
