# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from .merge_extract_result import MergeExtractResult
from .merge_extract_step_run_step import MergeExtractStepRunStep
from .step_run_base import StepRunBase


class MergeExtractStepRun(StepRunBase):
    step: MergeExtractStepRunStep
    result: typing.Optional[MergeExtractResult] = pydantic.Field(default=None)
    """
    The merge extract result. Will be null if the merge extract step was not successful.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


update_forward_refs(MergeExtractStepRun)
