# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class ParseConfigChunkingStrategyType(enum.StrEnum):
    """
    The type of chunking strategy. Supported values:

    * `page`: Chunk document by pages.
    * `document`: Entire document is a single chunk. Essentially no chunking.
    * `section`: Split by logical sections. Not supported for target=spatial.
    """

    PAGE = "page"
    DOCUMENT = "document"
    SECTION = "section"
    _UNKNOWN = "__PARSECONFIGCHUNKINGSTRATEGYTYPE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "ParseConfigChunkingStrategyType":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        page: typing.Callable[[], T_Result],
        document: typing.Callable[[], T_Result],
        section: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is ParseConfigChunkingStrategyType.PAGE:
            return page()
        if self is ParseConfigChunkingStrategyType.DOCUMENT:
            return document()
        if self is ParseConfigChunkingStrategyType.SECTION:
            return section()
        return _unknown_member(self._value_)
