# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .split_run import SplitRun
from .split_step_run_step import SplitStepRunStep
from .step_run_base import StepRunBase


class SplitStepRun(StepRunBase):
    step: SplitStepRunStep
    result: typing.Optional[SplitRun] = pydantic.Field(default=None)
    """
    The split run that was executed. Will be null if the split step was not successful.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
