# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .created_at import CreatedAt
from .split_config import SplitConfig


class SplitterVersion(UncheckedBaseModel):
    object: typing.Literal["splitter_version"] = pydantic.Field(default="splitter_version")
    """
    The type of object. Will always be `"splitter_version"`.
    """

    id: str = pydantic.Field()
    """
    The unique identifier for this version of the splitter.
    
    Example: `"splitter_vsn_xK9mLPqRtN3vS8wF5hB2cQ"`
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    A description of this version of the splitter.
    
    Example: `"Updated split rules for multi-invoice packets"`
    """

    version: str = pydantic.Field()
    """
    The version number or identifier for this specific version of the splitter. The draft version will have version="draft".
    
    Examples: `"1.0"`, `"2.1"`, `"draft"`
    """

    config: SplitConfig = pydantic.Field()
    """
    The configuration settings for this version of the splitter.
    """

    splitter_id: typing_extensions.Annotated[str, FieldMetadata(alias="splitterId")] = pydantic.Field(
        alias="splitterId"
    )
    """
    The ID of the splitter that this version belongs to.
    
    Example: `"splitter_Xj8mK2pL9nR4vT7qY5wZ"`
    """

    created_at: typing_extensions.Annotated[CreatedAt, FieldMetadata(alias="createdAt")] = pydantic.Field(
        alias="createdAt"
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
