# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .created_at import CreatedAt
from .splitter_version import SplitterVersion
from .updated_at import UpdatedAt


class Splitter(UncheckedBaseModel):
    object: typing.Literal["splitter"] = pydantic.Field(default="splitter")
    """
    The type of object. Will always be `"splitter"`.
    """

    id: str = pydantic.Field()
    """
    The ID of the splitter.
    
    Example: `"splitter_Xj8mK2pL9nR4vT7qY5wZ"`
    """

    name: str = pydantic.Field()
    """
    The name of the splitter.
    
    Example: `"Invoice Packet Splitter"`
    """

    created_at: typing_extensions.Annotated[CreatedAt, FieldMetadata(alias="createdAt")] = pydantic.Field(
        alias="createdAt"
    )
    updated_at: typing_extensions.Annotated[UpdatedAt, FieldMetadata(alias="updatedAt")] = pydantic.Field(
        alias="updatedAt"
    )
    draft_version: typing_extensions.Annotated[SplitterVersion, FieldMetadata(alias="draftVersion")] = pydantic.Field(
        alias="draftVersion"
    )
    """
    The draft version of the splitter. This is the editable version in the Extend dashboard.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
