# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.extract_run_summary import ExtractRunSummary
from ...types.next_page_token import NextPageToken


class ExtractRunsListResponse(UniversalBaseModel):
    extract_runs: typing_extensions.Annotated[typing.List[ExtractRunSummary], FieldMetadata(alias="extractRuns")] = (
        pydantic.Field(alias="extractRuns")
    )
    next_page_token: typing_extensions.Annotated[
        typing.Optional[NextPageToken], FieldMetadata(alias="nextPageToken")
    ] = pydantic.Field(alias="nextPageToken", default=None)

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
