# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .parse_runs_create_batch_request_inputs_item import ParseRunsCreateBatchRequestInputsItemParams
    from .parse_runs_create_batch_request_inputs_item_file import ParseRunsCreateBatchRequestInputsItemFileParams
    from .parse_runs_create_request_file import ParseRunsCreateRequestFileParams
    from .parse_runs_delete_response import ParseRunsDeleteResponseParams
    from .parse_runs_list_response import ParseRunsListResponseParams
_dynamic_imports: typing.Dict[str, str] = {
    "ParseRunsCreateBatchRequestInputsItemFileParams": ".parse_runs_create_batch_request_inputs_item_file",
    "ParseRunsCreateBatchRequestInputsItemParams": ".parse_runs_create_batch_request_inputs_item",
    "ParseRunsCreateRequestFileParams": ".parse_runs_create_request_file",
    "ParseRunsDeleteResponseParams": ".parse_runs_delete_response",
    "ParseRunsListResponseParams": ".parse_runs_list_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ParseRunsCreateBatchRequestInputsItemFileParams",
    "ParseRunsCreateBatchRequestInputsItemParams",
    "ParseRunsCreateRequestFileParams",
    "ParseRunsDeleteResponseParams",
    "ParseRunsListResponseParams",
]
