# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...types.run_metadata import RunMetadata
from .parse_runs_create_batch_request_inputs_item_file import ParseRunsCreateBatchRequestInputsItemFileParams


class ParseRunsCreateBatchRequestInputsItemParams(typing_extensions.TypedDict):
    file: ParseRunsCreateBatchRequestInputsItemFileParams
    """
    The file to parse. Can be a URL, an Extend file ID, or raw text.
    """

    metadata: typing_extensions.NotRequired[RunMetadata]
