# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata


class BarcodeDetailsParams(typing_extensions.TypedDict):
    """
    Details for barcode blocks
    """

    type: typing.Literal["barcode_details"]
    """
    Indicates this is a barcode details object
    """

    image_url: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="imageUrl")]]
    """
    URL to the clipped/segmented barcode image. Only set if the option `imageClippingEnabled` in blockOptions.barcodes is `true`.
    """

    decoded_value: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="decodedValue")]]
    """
    The decoded value of the barcode or QR code. Only set if the option `readingEnabled` in blockOptions.barcodes is `true`.
    """

    format: typing_extensions.NotRequired[str]
    """
    The format of the barcode (e.g., "QRCode", "Code128", "DataMatrix", "EAN13").
    """
