# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata
from ..types.created_at import CreatedAt
from ..types.processor_run_status import ProcessorRunStatus
from ..types.run_metadata import RunMetadata
from ..types.updated_at import UpdatedAt
from .classifier_summary import ClassifierSummaryParams
from .classifier_version_summary import ClassifierVersionSummaryParams
from .classify_config import ClassifyConfigParams
from .classify_output import ClassifyOutputParams
from .file_summary import FileSummaryParams
from .run_usage import RunUsageParams


class ClassifyRunParams(typing_extensions.TypedDict):
    """
    Classify run object.
    """

    object: typing.Literal["classify_run"]
    """
    The type of object. Will always be `"classify_run"`.
    """

    id: str
    """
    The unique identifier for this classify run.
    
    Example: `"clr_Xj8mK2pL9nR4vT7qY5wZ"`
    """

    classifier: typing.Optional[ClassifierSummaryParams]
    """
    The classifier that was used for this run.
    
    **Availability:** Present when a classifier reference was provided. Not present when using inline `config`.
    """

    classifier_version: typing_extensions.Annotated[
        typing.Optional[ClassifierVersionSummaryParams], FieldMetadata(alias="classifierVersion")
    ]
    """
    The version of the classifier that was used for this run.
    
    **Availability:** Present when a classifier reference was provided. Not present when using inline `config`.
    """

    status: ProcessorRunStatus
    output: typing.Optional[ClassifyOutputParams]
    """
    The final output, either reviewed or initial.
    
    **Availability:** Present when `status` is `"PROCESSED"`.
    """

    initial_output: typing_extensions.Annotated[
        typing.Optional[ClassifyOutputParams], FieldMetadata(alias="initialOutput")
    ]
    """
    The initial output from the classify run, before any review edits.
    
    **Availability:** Present when `reviewed` is `true`.
    """

    reviewed_output: typing_extensions.Annotated[
        typing.Optional[ClassifyOutputParams], FieldMetadata(alias="reviewedOutput")
    ]
    """
    The output after human review.
    
    **Availability:** Present when `reviewed` is `true`.
    """

    failure_reason: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="failureReason")]
    """
    The reason for failure.
    
    **Availability:** Present when `status` is `"FAILED"`.
    
    Possible values include:
    * `ABORTED` - The run was aborted by the user
    * `INTERNAL_ERROR` - An unexpected internal error occurred
    * `FAILED_TO_PROCESS_FILE` - Failed to process the file (e.g., OCR failure, file access issues)
    * `INVALID_PROCESSOR` - The processor configuration is invalid
    * `INVALID_CONFIGURATION` - The provided configuration is incompatible with the selected model
    * `PARSING_ERROR` - Failed to parse the classification output
    * `PRE_PROCESSING_FAILURE` - An error occurred during preprocessing
    * `POST_PROCESSING_FAILURE` - An error occurred during postprocessing
    * `OUT_OF_CREDITS` - Insufficient credits to run the classification
    
    **Note:** Additional failure reasons may be added in the future. Your integration should handle unknown values gracefully.
    """

    failure_message: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="failureMessage")]
    """
    A detailed message about the failure.
    
    **Availability:** Present when `status` is `"FAILED"`.
    """

    metadata: typing.Optional[RunMetadata]
    """
    Any metadata that was provided when creating the classify run.
    
    **Availability:** Present when metadata was provided during creation.
    """

    reviewed: bool
    """
    Indicates whether the run has been reviewed by a human.
    """

    edited: bool
    """
    Indicates whether the run results have been edited during review.
    """

    config: ClassifyConfigParams
    """
    The configuration used for this classify run.
    """

    file: FileSummaryParams
    """
    The file that was processed.
    """

    parse_run_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="parseRunId")]
    """
    The ID of the parse run that was used for this classify run.
    
    **Availability:** Present when a parse run was created.
    """

    dashboard_url: typing_extensions.Annotated[str, FieldMetadata(alias="dashboardUrl")]
    """
    The URL to view the classify run in the Extend dashboard.
    """

    usage: typing.Optional[RunUsageParams]
    """
    Usage credits consumed by this run.
    
    **Availability:** This field will not be returned for:
    * Runs created before October 7, 2025
    * Customers on legacy billing systems
    """

    created_at: typing_extensions.Annotated[CreatedAt, FieldMetadata(alias="createdAt")]
    updated_at: typing_extensions.Annotated[UpdatedAt, FieldMetadata(alias="updatedAt")]
