# This file was auto-generated by Fern from our API Definition.

import typing

from .conditional_extract_result import ConditionalExtractResultParams
from .conditional_extract_step_run_step import ConditionalExtractStepRunStepParams
from .step_run_base import StepRunBaseParams


class ConditionalExtractStepRunParams(StepRunBaseParams):
    step: ConditionalExtractStepRunStepParams
    result: typing.Optional[ConditionalExtractResultParams]
    """
    The conditional extract result. Will be null if the conditional extract step was not successful.
    """
