# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..core.serialization import FieldMetadata


class ConditionalNextEntryParams(typing_extensions.TypedDict):
    """
    A next entry for `CONDITIONAL` steps. Routes based on which condition branch matched.

    See the [Configuring Workflows via API guide](https://docs.extend.ai/2026-02-09/product/workflows/configuring-workflows-via-api) for end-to-end examples.
    """

    step: str
    """
    The name of the target step.
    """

    condition_id: typing_extensions.Annotated[str, FieldMetadata(alias="conditionId")]
    """
    Must match one of the `config.conditions[].id` values on the conditional step.
    """
