# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .conditional_extract_step_definition_config import ConditionalExtractStepDefinitionConfigParams
from .simple_next_entry import SimpleNextEntryParams


class ConditionalExtractStepDefinitionParams(typing_extensions.TypedDict):
    """
    Runs extractors based on formula conditions.

    Each extractor reference must include an explicit `version`. Valid values are `"latest"`, `"draft"`, or a specific semver string (e.g. `"1.0"`). Rules only support saved extractor references — inline configs are not supported in `CONDITIONAL_EXTRACT` rules.

    See the [Conditional Extract step docs](https://docs.extend.ai/2026-02-09/workflows/configuring-workflows#conditional-extract).
    """

    name: str
    config: typing_extensions.NotRequired[ConditionalExtractStepDefinitionConfigParams]
    """
    Optional on create/update. Required before the workflow can be deployed. Omitted in responses when the step is not yet configured.
    """

    next: typing_extensions.NotRequired[typing.Sequence[SimpleNextEntryParams]]
    """
    Can only be set when `config` is present.
    """
