# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..core.serialization import FieldMetadata
from .edit_root_json import EditRootJsonParams
from .edit_schema_generation_config_advanced_options import EditSchemaGenerationConfigAdvancedOptionsParams


class EditSchemaGenerationConfigParams(typing_extensions.TypedDict):
    """
    Configuration options for edit schema generation.
    """

    engine_version: typing_extensions.NotRequired[
        typing_extensions.Annotated[str, FieldMetadata(alias="engineVersion")]
    ]
    """
    The Edit engine version to use for form detection. Use an exact version for reproducible results, or `latest` to use the latest stable version. Defaults to `0.0.1` when omitted. Responses contain the resolved exact version.
    """

    input_schema: typing_extensions.NotRequired[
        typing_extensions.Annotated[EditRootJsonParams, FieldMetadata(alias="inputSchema")]
    ]
    """
    Optional existing edit schema to map onto the detected form fields. When provided, the response may include a `mappingResult`
    that shows which input schema paths matched the generated form fields.
    """

    instructions: typing_extensions.NotRequired[str]
    """
    Custom instructions provided for schema generation.
    """

    advanced_options: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            EditSchemaGenerationConfigAdvancedOptionsParams, FieldMetadata(alias="advancedOptions")
        ]
    ]
    """
    Advanced options for schema generation.
    """
