# This file was auto-generated by Fern from our API Definition.

import typing

from .external_data_validation_result import ExternalDataValidationResultParams
from .external_data_validation_step_run_step import ExternalDataValidationStepRunStepParams
from .step_run_base import StepRunBaseParams


class ExternalDataValidationStepRunParams(StepRunBaseParams):
    step: ExternalDataValidationStepRunStepParams
    result: typing.Optional[ExternalDataValidationResultParams]
    """
    The external data validation result. Will be null if the external data validation step was not successful.
    """
