# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .extract_step_definition_config import ExtractStepDefinitionConfigParams
from .simple_next_entry import SimpleNextEntryParams


class ExtractStepDefinitionParams(typing_extensions.TypedDict):
    """
    Extracts structured data from parsed content using an extractor.

    The extractor reference must include an explicit `version`. Valid values are `"latest"`, `"draft"`, or a specific semver string (e.g. `"1.0"`).

    See the [Extract step docs](https://docs.extend.ai/2026-02-09/workflows/configuring-workflows#extract).
    """

    name: str
    config: typing_extensions.NotRequired[ExtractStepDefinitionConfigParams]
    """
    Optional on create/update. Required before the workflow can be deployed. Omitted in responses when the step is not yet configured.
    """

    next: typing_extensions.NotRequired[typing.Sequence[SimpleNextEntryParams]]
    """
    Can only be set when `config` is present.
    """
