# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata
from ..types.created_at import CreatedAt
from ..types.updated_at import UpdatedAt


class ExtractorSummaryParams(typing_extensions.TypedDict):
    object: typing.Literal["extractor"]
    """
    The type of object. Will always be `"extractor"`.
    """

    id: str
    """
    The ID of the extractor.
    
    Example: `"ex_Xj8mK2pL9nR4vT7qY5wZ"`
    """

    name: str
    """
    The name of the extractor.
    
    Example: `"Invoice Extractor"`
    """

    created_at: typing_extensions.Annotated[CreatedAt, FieldMetadata(alias="createdAt")]
    updated_at: typing_extensions.Annotated[UpdatedAt, FieldMetadata(alias="updatedAt")]
