# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class ParseConfigAdvancedOptionsFormattingDetectionItemParams(typing_extensions.TypedDict):
    type: typing.Literal["change_tracking"]
    """
    The type of formatting detection to enable.
    
    * `"change_tracking"` — Detect tracked changes (insertions, deletions, substitutions) indicated by strikethroughs, colored text, or underlines in the source document.
    """
