# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class ParseConfigBlockOptionsFormulasParams(typing_extensions.TypedDict):
    """
    Options for formula blocks.
    """

    enabled: typing_extensions.NotRequired[bool]
    """
    Whether to enable formula detection and parsing. When enabled, mathematical formulas and equations are detected and their LaTeX representations are included in the output. When disabled, formulas will be detected as text blocks and may not be accurately parsed.
    """
