# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .workflow_step_base import WorkflowStepBaseParams


class ParseStepRunStepParams(WorkflowStepBaseParams):
    type: typing_extensions.NotRequired[typing.Literal["PARSE"]]
    """
    The type of workflow step. Will always be `"PARSE"` for this step run type.
    """
