# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .rule_validation_step_definition_config_rules_item import RuleValidationStepDefinitionConfigRulesItemParams


class RuleValidationStepDefinitionConfigParams(typing_extensions.TypedDict):
    """
    Optional on create/update. Required before the workflow can be deployed. Omitted in responses when the step is not yet configured.
    """

    rules: typing.Sequence[RuleValidationStepDefinitionConfigRulesItemParams]
    """
    Validation rules for this step. Each rule defines a name and a boolean formula.
    
    See the [Rule Validation step docs](https://docs.extend.ai/2026-02-09/workflows/configuring-workflows#rule-validation).
    """
