# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.run_usage_breakdown_entry_object import RunUsageBreakdownEntryObject
from .run_usage_breakdown_charge import RunUsageBreakdownChargeParams


class RunUsageBreakdownEntryParams(typing_extensions.TypedDict):
    """
    One line item in a run's `usage.breakdown`. Each entry corresponds to a concrete chargeable resource that contributed credits to the parent operation. When `charges` is present, it itemizes the cost drivers behind this entry's `credits`.
    """

    object: RunUsageBreakdownEntryObject
    """
    The public object type of the contributing resource. Mirrors the top-level `object` field on the corresponding endpoint so callers can fetch the underlying resource by id if they want more detail.
    """

    id: str
    """
    The id of the contributing resource (e.g. `pr_3UZSj69pYZDKHFuuX57ic`).
    """

    credits: float
    """
    Credits charged to the contributing resource.
    """

    charges: typing_extensions.NotRequired[typing.Sequence[RunUsageBreakdownChargeParams]]
    """
    Itemized cost drivers that make up this entry's `credits`. When present, `sum(charges[].credits) === credits`.
    
    **Availability:** Present on runs persisted on or after June 10, 2026. Runs persisted before that date will omit this field.
    """
