# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.run_usage_breakdown_entry_object import RunUsageBreakdownEntryObject


class RunUsageBreakdownEntryParams(typing_extensions.TypedDict):
    """
    One line item in a run's `usage.breakdown`. Each entry corresponds to a concrete chargeable resource that contributed credits to the parent operation.
    """

    object: RunUsageBreakdownEntryObject
    """
    The public object type of the contributing resource. Mirrors the top-level `object` field on the corresponding endpoint so callers can fetch the underlying resource by id if they want more detail.
    """

    id: str
    """
    The id of the contributing resource (e.g. `pr_3UZSj69pYZDKHFuuX57ic`).
    """

    credits: float
    """
    Credits charged to the contributing resource.
    """
