# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata
from ..types.created_at import CreatedAt
from ..types.updated_at import UpdatedAt
from .created_by import CreatedByParams
from .workflow_version import WorkflowVersionParams


class WorkflowParams(typing_extensions.TypedDict):
    """
    A workflow with its draft version and steps.
    """

    object: typing.Literal["workflow"]
    """
    The type of object. Always `"workflow"`.
    """

    id: str
    """
    The ID of the workflow.
    """

    name: str
    """
    The name of the workflow.
    """

    created_at: typing_extensions.Annotated[CreatedAt, FieldMetadata(alias="createdAt")]
    updated_at: typing_extensions.Annotated[UpdatedAt, FieldMetadata(alias="updatedAt")]
    draft_version: typing_extensions.Annotated[WorkflowVersionParams, FieldMetadata(alias="draftVersion")]
    created_by: typing_extensions.Annotated[typing.Optional[CreatedByParams], FieldMetadata(alias="createdBy")]
