# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..requests.edit_schema_generation_config import EditSchemaGenerationConfigParams
from ..types.form_detection_run import FormDetectionRun
from .raw_client import AsyncRawFormDetectionRunsClient, RawFormDetectionRunsClient
from .requests.form_detection_runs_create_request_file import FormDetectionRunsCreateRequestFileParams

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FormDetectionRunsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFormDetectionRunsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFormDetectionRunsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFormDetectionRunsClient
        """
        return self._raw_client

    def create(
        self,
        *,
        file: FormDetectionRunsCreateRequestFileParams,
        config: typing.Optional[EditSchemaGenerationConfigParams] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FormDetectionRun:
        """
        Start detecting fields in a PDF form and return immediately with a `form_detection_run` resource, typically in the `PROCESSING` state.

        Poll `GET /form_detection_runs/{id}` until the status is `PROCESSED` or `FAILED`. When processing succeeds, `output.schema` contains an edit schema you can pass directly to `POST /edit` or `POST /edit_runs`.

        Parameters
        ----------
        file : FormDetectionRunsCreateRequestFileParams
            The PDF form to analyze. Files can be provided as a URL or an Extend file ID.

        config : typing.Optional[EditSchemaGenerationConfigParams]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FormDetectionRun
            Successfully initiated form detection run

        Examples
        --------
        from extend_ai import Extend

        client = Extend(
            token="YOUR_TOKEN",
        )
        client.form_detection_runs.create(
            file={"url": "https://example.com/form.pdf"},
            config={
                "instructions": "Detect the form fields and use human-readable field names.",
                "advanced_options": {"radio_enums_enabled": True},
            },
        )
        """
        _response = self._raw_client.create(file=file, config=config, request_options=request_options)
        return _response.data

    def retrieve(
        self,
        id: str,
        *,
        extend_workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FormDetectionRun:
        """
        Retrieve the status and results of a form detection run.

        Use this endpoint to poll a run created with `POST /form_detection_runs`. When `status` is `PROCESSED`, `output.schema` contains the generated edit schema.

        Parameters
        ----------
        id : str
            The unique identifier for the form detection run.

            Example: `"sgr_xK9mLPqRtN3vS8wF5hB2cQ"`

        extend_workspace_id : typing.Optional[str]
            The workspace ID to target. **Required** when using an organization-scoped API key; optional for workspace-scoped keys (the key is already tied to a workspace). See [Authentication](https://docs.extend.ai/2026-02-09/api-reference/authentication) for details on API key scopes.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FormDetectionRun
            Successfully retrieved form detection run

        Examples
        --------
        from extend_ai import Extend

        client = Extend(
            token="YOUR_TOKEN",
        )
        client.form_detection_runs.retrieve(
            id="sgr_xK9mLPqRtN3vS8wF5hB2cQ",
        )
        """
        _response = self._raw_client.retrieve(
            id, extend_workspace_id=extend_workspace_id, request_options=request_options
        )
        return _response.data


class AsyncFormDetectionRunsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFormDetectionRunsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFormDetectionRunsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFormDetectionRunsClient
        """
        return self._raw_client

    async def create(
        self,
        *,
        file: FormDetectionRunsCreateRequestFileParams,
        config: typing.Optional[EditSchemaGenerationConfigParams] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FormDetectionRun:
        """
        Start detecting fields in a PDF form and return immediately with a `form_detection_run` resource, typically in the `PROCESSING` state.

        Poll `GET /form_detection_runs/{id}` until the status is `PROCESSED` or `FAILED`. When processing succeeds, `output.schema` contains an edit schema you can pass directly to `POST /edit` or `POST /edit_runs`.

        Parameters
        ----------
        file : FormDetectionRunsCreateRequestFileParams
            The PDF form to analyze. Files can be provided as a URL or an Extend file ID.

        config : typing.Optional[EditSchemaGenerationConfigParams]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FormDetectionRun
            Successfully initiated form detection run

        Examples
        --------
        import asyncio

        from extend_ai import AsyncExtend

        client = AsyncExtend(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.form_detection_runs.create(
                file={"url": "https://example.com/form.pdf"},
                config={
                    "instructions": "Detect the form fields and use human-readable field names.",
                    "advanced_options": {"radio_enums_enabled": True},
                },
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(file=file, config=config, request_options=request_options)
        return _response.data

    async def retrieve(
        self,
        id: str,
        *,
        extend_workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FormDetectionRun:
        """
        Retrieve the status and results of a form detection run.

        Use this endpoint to poll a run created with `POST /form_detection_runs`. When `status` is `PROCESSED`, `output.schema` contains the generated edit schema.

        Parameters
        ----------
        id : str
            The unique identifier for the form detection run.

            Example: `"sgr_xK9mLPqRtN3vS8wF5hB2cQ"`

        extend_workspace_id : typing.Optional[str]
            The workspace ID to target. **Required** when using an organization-scoped API key; optional for workspace-scoped keys (the key is already tied to a workspace). See [Authentication](https://docs.extend.ai/2026-02-09/api-reference/authentication) for details on API key scopes.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FormDetectionRun
            Successfully retrieved form detection run

        Examples
        --------
        import asyncio

        from extend_ai import AsyncExtend

        client = AsyncExtend(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.form_detection_runs.retrieve(
                id="sgr_xK9mLPqRtN3vS8wF5hB2cQ",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve(
            id, extend_workspace_id=extend_workspace_id, request_options=request_options
        )
        return _response.data
