# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ...core.serialization import FieldMetadata
from ...requests.extractor_version_summary import ExtractorVersionSummaryParams
from ...types.next_page_token import NextPageToken


class ExtractorVersionsListResponseParams(typing_extensions.TypedDict):
    object: typing.Literal["list"]
    data: typing.Sequence[ExtractorVersionSummaryParams]
    next_page_token: typing_extensions.NotRequired[
        typing_extensions.Annotated[NextPageToken, FieldMetadata(alias="nextPageToken")]
    ]
