# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.edit_schema_generation_config import EditSchemaGenerationConfig
from ..types.edit_schema_generation_response import EditSchemaGenerationResponse
from .raw_client import AsyncRawEditSchemasClient, RawEditSchemasClient
from .types.edit_schemas_generate_request_file import EditSchemasGenerateRequestFile

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EditSchemasClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEditSchemasClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEditSchemasClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEditSchemasClient
        """
        return self._raw_client

    def generate(
        self,
        *,
        file: EditSchemasGenerateRequestFile,
        config: typing.Optional[EditSchemaGenerationConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EditSchemaGenerationResponse:
        """
        Detect fields in a PDF form and synchronously return an edit schema payload.

        Use this endpoint when you want Extend to bootstrap an `EditRootJSONSchema` from an existing form, optionally mapping an existing schema onto the detected fields.

        This endpoint returns the generated schema directly. There are no schema generation run resources to poll or delete.

        Parameters
        ----------
        file : EditSchemasGenerateRequestFile
            A file object containing either a URL or a fileId.

        config : typing.Optional[EditSchemaGenerationConfig]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EditSchemaGenerationResponse
            Successfully generated edit schema

        Examples
        --------
        from extend_ai import (
            EditSchemaGenerationConfig,
            EditSchemaGenerationConfigAdvancedOptions,
            Extend,
        )
        from extend_ai.edit_schemas import EditSchemasGenerateRequestFile

        client = Extend(
            token="YOUR_TOKEN",
        )
        client.edit_schemas.generate(
            file=EditSchemasGenerateRequestFile(
                file_url="https://example.com/form.pdf",
            ),
            config=EditSchemaGenerationConfig(
                instructions="Detect the form fields and use human-readable field names.",
                advanced_options=EditSchemaGenerationConfigAdvancedOptions(
                    radio_enums_enabled=True,
                ),
            ),
        )
        """
        _response = self._raw_client.generate(file=file, config=config, request_options=request_options)
        return _response.data


class AsyncEditSchemasClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEditSchemasClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEditSchemasClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEditSchemasClient
        """
        return self._raw_client

    async def generate(
        self,
        *,
        file: EditSchemasGenerateRequestFile,
        config: typing.Optional[EditSchemaGenerationConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EditSchemaGenerationResponse:
        """
        Detect fields in a PDF form and synchronously return an edit schema payload.

        Use this endpoint when you want Extend to bootstrap an `EditRootJSONSchema` from an existing form, optionally mapping an existing schema onto the detected fields.

        This endpoint returns the generated schema directly. There are no schema generation run resources to poll or delete.

        Parameters
        ----------
        file : EditSchemasGenerateRequestFile
            A file object containing either a URL or a fileId.

        config : typing.Optional[EditSchemaGenerationConfig]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EditSchemaGenerationResponse
            Successfully generated edit schema

        Examples
        --------
        import asyncio

        from extend_ai import (
            AsyncExtend,
            EditSchemaGenerationConfig,
            EditSchemaGenerationConfigAdvancedOptions,
        )
        from extend_ai.edit_schemas import EditSchemasGenerateRequestFile

        client = AsyncExtend(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.edit_schemas.generate(
                file=EditSchemasGenerateRequestFile(
                    file_url="https://example.com/form.pdf",
                ),
                config=EditSchemaGenerationConfig(
                    instructions="Detect the form fields and use human-readable field names.",
                    advanced_options=EditSchemaGenerationConfigAdvancedOptions(
                        radio_enums_enabled=True,
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.generate(file=file, config=config, request_options=request_options)
        return _response.data
