# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from ...core.serialization import FieldMetadata
from .workflow_runs_cancel_response_workflow_run import WorkflowRunsCancelResponseWorkflowRun


class WorkflowRunsCancelResponse(UniversalBaseModel):
    workflow_run: typing_extensions.Annotated[
        WorkflowRunsCancelResponseWorkflowRun, FieldMetadata(alias="workflowRun")
    ] = pydantic.Field(alias="workflowRun")

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


update_forward_refs(WorkflowRunsCancelResponse)
