# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ...core.serialization import FieldMetadata
from ...requests.extractor_summary import ExtractorSummaryParams
from ...types.next_page_token import NextPageToken


class ExtractorsListResponseParams(typing_extensions.TypedDict):
    object: typing.Literal["list"]
    data: typing.Sequence[ExtractorSummaryParams]
    next_page_token: typing_extensions.NotRequired[
        typing_extensions.Annotated[NextPageToken, FieldMetadata(alias="nextPageToken")]
    ]
